### ISSUE TITLE
JSON data issue on Hosted Form Builder code

### ISSUE THREAD

**Issue by cybrpimp** [StephenOTT/camunda-formio-plugin#38] opened 2020-10-07 06:10 UTC
@StephenOTT I've been doing testing and I have the plug-in installed correctly and your "SomeProcess1" demo process working.  When I start the process, there is a nice fancy form.

So as a test, I went to the hosted form builder URL and made a small test form and was simply going to replace the code in your MyStartForm.json file with the code of the form I built and re-deploy to see if I could work from your demo.

When I try to start the process, it does not render.

Replacing your original MyStartForm.json works again.  Ok, so we have a definite issue.

I opened both my version and your version of the MyStartForm.json file and compared it.  Below is the code for my version of the form.

The one things I noticed was my hosted builder code had 5 extra lines of code that were extra data elements at the top;

`    display form,
    settings {
        pdf {
            id 1ec0f8ee-6685-5d98-a847-26f67b67d6f0,
            src httpsfiles.form.iopdf5692b91fd1028f01000407e3file1ec0f8ee-6685-5d98-a847-26f67b67d6f0
        }
    },`

When I removed these lines and which made the code more in-line with your original format and deploy the code where it displays the simple form.

So I'm not sure if the Hosted Form Builder is possibly on a new/older version or what, but there definately seems like there might be an issue with rending the Hosted Form Builder JSON Code.

Below is the original code from the Hosted Form Builder.

`{
    display form,
    settings {
        pdf {
            id 1ec0f8ee-6685-5d98-a847-26f67b67d6f0,
            src httpsfiles.form.iopdf5692b91fd1028f01000407e3file1ec0f8ee-6685-5d98-a847-26f67b67d6f0
        }
    },
    components [
        {
            label Name,
            placeholder Texas,
            description Please type your name.,
            tooltip Please type your name.,
            tableView true,
            key name,
            type textfield,
            input true
        },
        {
            type button,
            label Submit,
            key submit,
            disableOnInvalid true,
            input true,
            tableView false
        }
    ]
}`

**Comment by StephenOTT** [comment] 2020-10-08 01:00
The hosted builder is using additional settings that is likely throwing an error. 

Try using the localhost/forms/builder.html

**Comment by cybrpimp** [comment] 2020-10-12 06:48
I'll try and get back if I experience problems.

Thanks for your time.

**Comment by cybrpimp** [comment] 2020-10-12 08:18
Ok, updating thread for others.  The "localhost/forms/builder.html" version of the Form Builder did seem to work in the Demo Process.

Though I have not gotten a form to successfully work when I copy to any other process, but it does work in the Demo.

**Comment by StephenOTT** [comment] 2020-10-12 14:01
Remember that you need to deploy the JSON with each BPMN that you deploy (when using the deployment= param).

**Comment by StephenOTT** [comment] 2020-10-12 14:02
Going to close this as what you are seeing is not a bug related to form builder or the hosted builder.  It is just brought in settings that are not relevant to a locally hosted form render.

**Closed by StephenOTT** 2020-10-12 14:02 UTC
